name: Check
on:
  push
jobs:
  scalafmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Scalafmt
        uses: coursier/setup-action@v1
        with:
          apps: scalafmt
      - name: Check Scalafmt
        run: scalafmt --test
