name: Check
on:
  push
jobs:
  scalafmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Check for scalafmt conformance
        uses: openlawteam/scalafmt-ci@v2.0.2
