name: Check
on:
  push
jobs:
  scalafmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Install Coursier
        run: |
          curl -fLo cs https://git.io/coursier-cli-"$(uname | tr LD ld)"
          chmod +x cs
      - name: Install scalafmt
        run: >
          ./cs install scalafmt
      - name: Run Scalafmt
        run: scalafmt --test
